# Generated by Django 4.2 on 2024-01-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='user_token',
        ),
    ]
