# Generated by Django 5.0 on 2023-12-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Превью')),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('on_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='статус')),
                ('count_view', models.IntegerField(blank=True, default=0, null=True, verbose_name='соличество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоговые записи',
            },
        ),
    ]
