# Generated by Django 5.0 on 2023-12-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='Blogs',
        ),
    ]
