# Generated by Django 5.0 on 2023-12-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_block_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='data',
            new_name='date',
        ),
    ]
