# Generated by Django 5.0 on 2023-12-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_data_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='count_view',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='blogs/', verbose_name='Превью'),
        ),
    ]
