# Generated by Django 5.0 on 2023-12-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descritpion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descritpion',
            new_name='description',
        ),
    ]
