# Generated by Django 4.2 on 2024-01-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_active', 'can publish post')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
