# Generated by Django 4.2 on 2024-01-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_active', 'can publish post'), ('change_category_product', 'can change category product'), ('change_description_product', 'can change description product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
